from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import ConditionsLogEntry


TOS_LABEL = (
    "I agree that sharing glideCast recommendations generated by this account "
    "for commercial coaching purposes without a team or club license is prohibited "
    "and may result in immediate account termination without refund."
)


class SignupFormWithToS(UserCreationForm):
    accept_tos = forms.BooleanField(
        required=True,
        label=TOS_LABEL,
        widget=forms.CheckboxInput(attrs={"class": "input-check-wrap"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["accept_tos"].required = True


class ConditionsLogEntryForm(forms.ModelForm):
    class Meta:
        model = ConditionsLogEntry
        fields = ["date", "venue", "discipline", "run1_wax", "run2_wax", "result", "snow_notes"]
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
            "venue": forms.TextInput(attrs={"placeholder": "Venue name"}),
            "discipline": forms.TextInput(attrs={"placeholder": "SL, GS, SuperG"}),
            "run1_wax": forms.TextInput(attrs={"placeholder": "Run 1 wax"}),
            "run2_wax": forms.TextInput(attrs={"placeholder": "Run 2 wax"}),
            "snow_notes": forms.Textarea(attrs={"rows": 2, "placeholder": "Snow conditions notes"}),
        }
