# Generated by Django 6.0.3 on 2026-07-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_screenshot_capture_signal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='screenshotcapturesignal',
            new_name='accounts_sc_user_id_3fdbcf_idx',
            old_name='accounts_sc_user_id_7e8b2d_idx',
        ),
    ]
