"""
Django settings for skiwax project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

_default_hosts = "localhost,127.0.0.1" if DEBUG else "*"
ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", _default_hosts).split(",") if h]
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "https://glidecast.net,https://www.glidecast.net").split(",") if o]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'accounts',
    'billing',
    'calculator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'accounts.middleware.SingleSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skiwax.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skiwax.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        ssl_require=os.environ.get("DATABASE_SSL_REQUIRE", "0") == "1",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = list(filter(Path.exists, [BASE_DIR / "static", BASE_DIR / "Photos"]))
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "paywall"
LOGOUT_REDIRECT_URL = "login"

EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@glidecast.com")

STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_BILLING_PORTAL_RETURN_URL = os.environ.get("STRIPE_BILLING_PORTAL_RETURN_URL", "")

# Basic ($5/mo) and Pro ($15/mo) × monthly. Create prices in Stripe and set env vars.
STRIPE_PRICE_BASIC_MONTHLY = os.environ.get("STRIPE_PRICE_BASIC_MONTHLY", "")
STRIPE_PRICE_BASIC_ANNUAL = os.environ.get("STRIPE_PRICE_BASIC_ANNUAL", "")
STRIPE_PRICE_PRO_MONTHLY = os.environ.get("STRIPE_PRICE_PRO_MONTHLY", "")
STRIPE_PRICE_PRO_ANNUAL = os.environ.get("STRIPE_PRICE_PRO_ANNUAL", "")

# Legacy env names (optional) — mapped in billing.views if new vars are empty
STRIPE_PRICE_CLUB_MONTHLY = os.environ.get("STRIPE_PRICE_CLUB_MONTHLY", "")
STRIPE_PRICE_CLUB_ANNUAL = os.environ.get("STRIPE_PRICE_CLUB_ANNUAL", "")
STRIPE_PRICE_INDIVIDUAL_MONTHLY = os.environ.get("STRIPE_PRICE_INDIVIDUAL_MONTHLY", "")
STRIPE_PRICE_INDIVIDUAL_ANNUAL = os.environ.get("STRIPE_PRICE_INDIVIDUAL_ANNUAL", "")
STRIPE_PRICE_COACH_MONTHLY = os.environ.get("STRIPE_PRICE_COACH_MONTHLY", "")
STRIPE_PRICE_COACH_ANNUAL = os.environ.get("STRIPE_PRICE_COACH_ANNUAL", "")
STRIPE_PRICE_RACE_DEPT_MONTHLY = os.environ.get("STRIPE_PRICE_RACE_DEPT_MONTHLY", "")
STRIPE_PRICE_RACE_DEPT_ANNUAL = os.environ.get("STRIPE_PRICE_RACE_DEPT_ANNUAL", "")

# Fallback single price → treated as Pro monthly if set
STRIPE_PRICE_ID = os.environ.get("STRIPE_PRICE_ID", "")

APP_BASE_URL = os.environ.get("APP_BASE_URL", "http://localhost:8000")

# When True, subscribed users see Pro calculator results (charts, detail, energy, PDF) regardless of plan.
# Set SHOW_PRO_CALCULATOR_RESULTS=0 in the environment to restore Basic vs Pro gating.
SHOW_PRO_CALCULATOR_RESULTS = os.environ.get("SHOW_PRO_CALCULATOR_RESULTS", "1") == "1"

# HTTPS / cookie security — auto-enabled when DEBUG=False
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Trust Railway's (and any other reverse-proxy's) X-Forwarded-Proto header so
# Django knows the original request was HTTPS and won't redirect-loop.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# django-axes brute-force protection
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_CALLABLE = None
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Security
WATERMARK_SECRET = os.environ.get("WATERMARK_SECRET", SECRET_KEY)
API_RATE_LIMIT_PER_HOUR = int(os.environ.get("API_RATE_LIMIT_PER_HOUR", "60"))
CONDITIONS_LOG_RETENTION_DAYS = 90
MAX_IP_LOGINS_PER_DAY_FLAG = 3

# Email for screenshot-key alerts (optional). If empty, events are logged in admin + server log only.
SCREENSHOT_ALERT_EMAIL = os.environ.get("SCREENSHOT_ALERT_EMAIL", "").strip()
