"""WaxOracle Nordic wax product database.

Snow type keys match classify_snow() output in engine.py:
  'new', 'cold_powder', 'packed', 'transformed',
  'hard_groomed', 'icy', 'wet', 'spring'

Temperature ranges are from manufacturer technical documentation.
Do not modify ranges without citing a manufacturer source.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# GLIDE WAX — skate (full ski) and classic (tip + tail zones)
# All products are fluoro-free (FIS 2023 rule compliant)
# ---------------------------------------------------------------------------

GLIDE_WAX: list[dict] = [

    # ── SWIX Performance Speed (PS) — race ─────────────────────────────────────────
    {"brand": "Swix", "product": "Performance Speed 5", "code": "PS5",
     "tier": "race", "temp_min": -30.0, "temp_max": -15.0, "humidity_max": 55,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.5, "transformed": 0.1,
              "hard_groomed": 0.2, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 6, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#172554",
     "notes": "Extreme cold, very dry — ultra-hard formula, very low humidity only"},

    {"brand": "Swix", "product": "Performance Speed 6", "code": "PS6",
     "tier": "race", "temp_min": -20.0, "temp_max": -10.0, "humidity_max": 65,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.7, "transformed": 0.2,
              "hard_groomed": 0.3, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 7, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1e3a8a",
     "notes": "Cold, dry powder or packed new snow — premier cold-range race glide"},

    {"brand": "Swix", "product": "Performance Speed 7", "code": "PS7",
     "tier": "race", "temp_min": -13.0, "temp_max": -5.0, "humidity_max": 75,
     "snow": {"new": 0.9, "cold_powder": 0.8, "packed": 1.0, "transformed": 0.5,
              "hard_groomed": 0.6, "icy": 0.3, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold, moderate humidity — most versatile cold-range race glide"},

    {"brand": "Swix", "product": "Performance Speed 8", "code": "PS8",
     "tier": "race", "temp_min": -9.0, "temp_max": -2.0, "humidity_max": 82,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium-cold — single most common race glide worldwide"},

    {"brand": "Swix", "product": "Performance Speed 10", "code": "PS10",
     "tier": "race", "temp_min": -4.0, "temp_max": +2.0, "humidity_max": 88,
     "snow": {"new": 0.5, "cold_powder": 0.2, "packed": 0.7, "transformed": 1.0,
              "hard_groomed": 0.6, "icy": 0.4, "wet": 0.7, "spring": 0.3},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#f59e0b",
     "notes": "Around-zero, transitional conditions — optimized for near-zero transformed snow"},

    {"brand": "Swix", "product": "Performance Speed 12", "code": "PS12",
     "tier": "race", "temp_min": 0.0, "temp_max": +6.0, "humidity_max": 95,
     "snow": {"new": 0.3, "cold_powder": 0.0, "packed": 0.4, "transformed": 0.7,
              "hard_groomed": 0.3, "icy": 0.2, "wet": 1.0, "spring": 1.0},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm and wet — spring or wet-snow conditions"},

    # ── SWIX TS (Training Speed) — training ─────────────────────────────────
    {"brand": "Swix", "product": "TS6", "code": "TS6",
     "tier": "training", "temp_min": -20.0, "temp_max": -10.0, "humidity_max": 70,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.7, "transformed": 0.2,
              "hard_groomed": 0.3, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 8, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1e3a8a",
     "notes": "Cold training glide — durable, wide-range formula"},

    {"brand": "Swix", "product": "TS7", "code": "TS7",
     "tier": "training", "temp_min": -13.0, "temp_max": -5.0, "humidity_max": 80,
     "snow": {"new": 0.9, "cold_powder": 0.8, "packed": 1.0, "transformed": 0.5,
              "hard_groomed": 0.6, "icy": 0.3, "wet": 0.0, "spring": 0.0},
     "durability": 9, "speed": 8, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold-range training — excellent durability for long sessions"},

    {"brand": "Swix", "product": "TS8", "code": "TS8",
     "tier": "training", "temp_min": -9.0, "temp_max": -2.0, "humidity_max": 85,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 9, "speed": 8, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium-cold training glide — most versatile training wax"},

    {"brand": "Swix", "product": "TS10", "code": "TS10",
     "tier": "training", "temp_min": -4.0, "temp_max": +2.0, "humidity_max": 90,
     "snow": {"new": 0.5, "cold_powder": 0.2, "packed": 0.7, "transformed": 1.0,
              "hard_groomed": 0.6, "icy": 0.4, "wet": 0.7, "spring": 0.3},
     "durability": 9, "speed": 8, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#f59e0b",
     "notes": "Around-zero training — long-lasting near-zero formula"},

    # ── VAUHTI Performance Race — race ──────────────────────────────────────────────
    {"brand": "Vauhti", "product": "Performance Race Cold", "code": "VPR-COLD",
     "tier": "race", "temp_min": -30.0, "temp_max": -10.0, "humidity_max": 60,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.8, "transformed": 0.3,
              "hard_groomed": 0.4, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 7, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1e3a8a",
     "notes": "Broad cold-range race glide — Finnish race team staple for cold/dry"},

    {"brand": "Vauhti", "product": "Performance Race Blue", "code": "VPR-BL",
     "tier": "race", "temp_min": -12.0, "temp_max": -4.0, "humidity_max": 75,
     "snow": {"new": 0.9, "cold_powder": 0.8, "packed": 1.0, "transformed": 0.5,
              "hard_groomed": 0.6, "icy": 0.3, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold-medium race glide — strong performer on packed/groomed cold snow"},

    {"brand": "Vauhti", "product": "Performance Race Violet", "code": "VPR-VI",
     "tier": "race", "temp_min": -6.0, "temp_max": 0.0, "humidity_max": 85,
     "snow": {"new": 0.6, "cold_powder": 0.3, "packed": 0.8, "transformed": 1.0,
              "hard_groomed": 0.7, "icy": 0.5, "wet": 0.3, "spring": 0.0},
     "durability": 8, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium race glide — widely tested in Scandinavian conditions near zero"},

    {"brand": "Vauhti", "product": "Performance Race Yellow", "code": "VPR-YE",
     "tier": "race", "temp_min": -2.0, "temp_max": +4.0, "humidity_max": 90,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.6, "transformed": 1.0,
              "hard_groomed": 0.5, "icy": 0.4, "wet": 0.8, "spring": 0.4},
     "durability": 7, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#c27803",
     "notes": "Warm-transitional race glide — excellent near-zero and high-humidity performance"},

    {"brand": "Vauhti", "product": "Performance Race Red", "code": "VPR-RE",
     "tier": "race", "temp_min": +1.0, "temp_max": +8.0, "humidity_max": 98,
     "snow": {"new": 0.2, "cold_powder": 0.0, "packed": 0.3, "transformed": 0.6,
              "hard_groomed": 0.2, "icy": 0.2, "wet": 1.0, "spring": 1.0},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Wet/warm conditions — high humidity and spring snow"},

    # ── TOKO High Performance NF — race ─────────────────────────────────────
    {"brand": "Toko", "product": "High Performance NF Blue Extra", "code": "HP-BX",
     "tier": "race", "temp_min": -30.0, "temp_max": -14.0, "humidity_max": 60,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.6, "transformed": 0.2,
              "hard_groomed": 0.3, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#172554",
     "notes": "Extreme cold dry snow — very hard formula for fine-grained new snow"},

    {"brand": "Toko", "product": "High Performance NF Blue", "code": "HP-BL",
     "tier": "race", "temp_min": -15.0, "temp_max": -5.0, "humidity_max": 75,
     "snow": {"new": 0.9, "cold_powder": 0.9, "packed": 1.0, "transformed": 0.4,
              "hard_groomed": 0.5, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold race glide — consistent performer across cold packed/groomed conditions"},

    {"brand": "Toko", "product": "High Performance NF Violet", "code": "HP-VI",
     "tier": "race", "temp_min": -7.0, "temp_max": -1.0, "humidity_max": 83,
     "snow": {"new": 0.6, "cold_powder": 0.4, "packed": 0.8, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium-cold race glide — proven in international race conditions"},

    {"brand": "Toko", "product": "High Performance NF Red", "code": "HP-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +4.0, "humidity_max": 90,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.4, "wet": 0.8, "spring": 0.4},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Transitional/warm race glide — wet and transformed snow near zero"},

    {"brand": "Toko", "product": "High Performance NF Yellow", "code": "HP-YE",
     "tier": "race", "temp_min": 0.0, "temp_max": +8.0, "humidity_max": 98,
     "snow": {"new": 0.2, "cold_powder": 0.0, "packed": 0.3, "transformed": 0.6,
              "hard_groomed": 0.2, "icy": 0.1, "wet": 1.0, "spring": 1.0},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#c27803",
     "notes": "Warm/wet race glide — spring and high-humidity conditions"},

    # ── RODE Cera G — race ──────────────────────────────────────────────────
    {"brand": "Rode", "product": "Cera G Cold Extra", "code": "CG-BX",
     "tier": "race", "temp_min": -30.0, "temp_max": -12.0, "humidity_max": 60,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.6, "transformed": 0.2,
              "hard_groomed": 0.3, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1e3a8a",
     "notes": "Extreme cold dry race glide — Italian-made, strong cold-new-snow formula"},

    {"brand": "Rode", "product": "Cera G Blue", "code": "CG-BL",
     "tier": "race", "temp_min": -12.0, "temp_max": -5.0, "humidity_max": 75,
     "snow": {"new": 0.9, "cold_powder": 0.8, "packed": 1.0, "transformed": 0.4,
              "hard_groomed": 0.5, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold race glide — broad cold range, excellent on groomed packed surfaces"},

    {"brand": "Rode", "product": "Cera G Violet", "code": "CG-VI",
     "tier": "race", "temp_min": -7.0, "temp_max": -1.0, "humidity_max": 83,
     "snow": {"new": 0.6, "cold_powder": 0.4, "packed": 0.8, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium-cold — widely used across Scandinavian and Alpine conditions"},

    {"brand": "Rode", "product": "Cera G Red", "code": "CG-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +3.0, "humidity_max": 90,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.4, "wet": 0.8, "spring": 0.3},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Near-zero wet/transformed conditions race glide"},

    {"brand": "Rode", "product": "Cera G Yellow", "code": "CG-YE",
     "tier": "race", "temp_min": 0.0, "temp_max": +8.0, "humidity_max": 98,
     "snow": {"new": 0.2, "cold_powder": 0.0, "packed": 0.3, "transformed": 0.6,
              "hard_groomed": 0.2, "icy": 0.1, "wet": 1.0, "spring": 1.0},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#c27803",
     "notes": "Wet/spring race glide — warm high-humidity conditions"},

    # ── REX NF Racing — race ────────────────────────────────────────────────
    {"brand": "Rex", "product": "NF Racing Green", "code": "NF-GR",
     "tier": "race", "temp_min": -30.0, "temp_max": -14.0, "humidity_max": 55,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.5, "transformed": 0.1,
              "hard_groomed": 0.2, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 6, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#14532d",
     "notes": "Extreme cold, very low humidity — specialized for Scandinavian arctic conditions"},

    {"brand": "Rex", "product": "NF Racing Blue", "code": "NF-BL",
     "tier": "race", "temp_min": -15.0, "temp_max": -6.0, "humidity_max": 72,
     "snow": {"new": 1.0, "cold_powder": 0.9, "packed": 1.0, "transformed": 0.4,
              "hard_groomed": 0.5, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold race glide — Finnish national team product, excellent on groomed cold tracks"},

    {"brand": "Rex", "product": "NF Racing Violet", "code": "NF-VI",
     "tier": "race", "temp_min": -8.0, "temp_max": -1.0, "humidity_max": 82,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium cold — Finnish engineering, consistent across medium conditions"},

    {"brand": "Rex", "product": "NF Racing Red", "code": "NF-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +3.0, "humidity_max": 90,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.4, "wet": 0.8, "spring": 0.3},
     "durability": 7, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm/wet race glide — near-zero and high humidity"},

    {"brand": "Rex", "product": "NF Racing Yellow", "code": "NF-YE",
     "tier": "race", "temp_min": 0.0, "temp_max": +8.0, "humidity_max": 98,
     "snow": {"new": 0.2, "cold_powder": 0.0, "packed": 0.3, "transformed": 0.5,
              "hard_groomed": 0.2, "icy": 0.1, "wet": 1.0, "spring": 1.0},
     "durability": 7, "speed": 10, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#c27803",
     "notes": "Wet/spring race glide"},

    # ── START SG Racing — race ───────────────────────────────────────────────
    {"brand": "Start", "product": "SG Racing Blue", "code": "SG-BL",
     "tier": "race", "temp_min": -30.0, "temp_max": -10.0, "humidity_max": 70,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.8, "transformed": 0.3,
              "hard_groomed": 0.4, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Broad cold-range race glide — Finnish wax company, race-proven formula"},

    {"brand": "Start", "product": "SG Racing Violet", "code": "SG-VI",
     "tier": "race", "temp_min": -10.0, "temp_max": -2.0, "humidity_max": 83,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium race glide — good value performance for medium-cold groomed conditions"},

    {"brand": "Start", "product": "SG Racing Red", "code": "SG-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +4.0, "humidity_max": 90,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.4, "wet": 0.8, "spring": 0.4},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm/transitional race glide"},

    # ── SKIGO XC Racer — race ────────────────────────────────────────────────
    {"brand": "SkiGo", "product": "XC Racer Blue", "code": "XCR-BL",
     "tier": "race", "temp_min": -30.0, "temp_max": -8.0, "humidity_max": 70,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.8, "transformed": 0.3,
              "hard_groomed": 0.4, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Broad cold-range Scandinavian race glide — Swedish national team history"},

    {"brand": "SkiGo", "product": "XC Racer Violet", "code": "XCR-VI",
     "tier": "race", "temp_min": -8.0, "temp_max": -2.0, "humidity_max": 83,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium race glide — well-proven in Swedish competition"},

    {"brand": "SkiGo", "product": "XC Racer Red", "code": "XCR-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +5.0, "humidity_max": 92,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.3, "wet": 0.9, "spring": 0.6},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm/wet race glide — strong in wet-snow Scandinavian conditions"},

    # ── MAPLUS HP3 — race ────────────────────────────────────────────────────
    {"brand": "Maplus", "product": "HP3 Blue", "code": "HP3-BL",
     "tier": "race", "temp_min": -15.0, "temp_max": -5.0, "humidity_max": 73,
     "snow": {"new": 0.9, "cold_powder": 0.9, "packed": 1.0, "transformed": 0.4,
              "hard_groomed": 0.5, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold race glide — Italian precision engineering for cold groomed conditions"},

    {"brand": "Maplus", "product": "HP3 Violet", "code": "HP3-VI",
     "tier": "race", "temp_min": -8.0, "temp_max": 0.0, "humidity_max": 83,
     "snow": {"new": 0.6, "cold_powder": 0.4, "packed": 0.8, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.3, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium-cold race glide — covers medium-to-zero range"},

    {"brand": "Maplus", "product": "HP3 Red", "code": "HP3-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +5.0, "humidity_max": 92,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.3, "wet": 0.9, "spring": 0.6},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm/wet race glide"},

    # ── HOLMENKOL Syntec Race — race ─────────────────────────────────────────
    {"brand": "Holmenkol", "product": "Syntec Race Blue", "code": "SY-BL",
     "tier": "race", "temp_min": -30.0, "temp_max": -10.0, "humidity_max": 68,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.8, "transformed": 0.3,
              "hard_groomed": 0.4, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold race glide — German engineering, broad cold range"},

    {"brand": "Holmenkol", "product": "Syntec Race Violet", "code": "SY-VI",
     "tier": "race", "temp_min": -10.0, "temp_max": -2.0, "humidity_max": 83,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium race glide"},

    {"brand": "Holmenkol", "product": "Syntec Race Red", "code": "SY-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +5.0, "humidity_max": 92,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.3, "wet": 0.9, "spring": 0.6},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm/wet race glide"},

    # ── STAR NF — race ───────────────────────────────────────────────────────
    {"brand": "Star", "product": "NF Blue", "code": "STAR-BL",
     "tier": "race", "temp_min": -30.0, "temp_max": -10.0, "humidity_max": 70,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.8, "transformed": 0.3,
              "hard_groomed": 0.4, "icy": 0.2, "wet": 0.0, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "Cold race glide — Italian brand, well-regarded by European club teams"},

    {"brand": "Star", "product": "NF Violet", "code": "STAR-VI",
     "tier": "race", "temp_min": -10.0, "temp_max": -2.0, "humidity_max": 83,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.2, "spring": 0.0},
     "durability": 8, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium race glide"},

    {"brand": "Star", "product": "NF Red", "code": "STAR-RE",
     "tier": "race", "temp_min": -3.0, "temp_max": +5.0, "humidity_max": 92,
     "snow": {"new": 0.4, "cold_powder": 0.1, "packed": 0.5, "transformed": 0.9,
              "hard_groomed": 0.4, "icy": 0.3, "wet": 0.9, "spring": 0.6},
     "durability": 7, "speed": 9, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#dc2626",
     "notes": "Warm/wet race glide"},

    # ── SWIX CH — recreational ───────────────────────────────────────────────
    {"brand": "Swix", "product": "CH6", "code": "CH6",
     "tier": "recreational", "temp_min": -25.0, "temp_max": -12.0, "humidity_max": 75,
     "snow": {"new": 1.0, "cold_powder": 1.0, "packed": 0.7, "transformed": 0.2,
              "hard_groomed": 0.3, "icy": 0.1, "wet": 0.0, "spring": 0.0},
     "durability": 9, "speed": 7, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1e3a8a",
     "notes": "Cold recreational glide — long-lasting, easy to apply"},

    {"brand": "Swix", "product": "CH7", "code": "CH7",
     "tier": "recreational", "temp_min": -12.0, "temp_max": -5.0, "humidity_max": 82,
     "snow": {"new": 0.9, "cold_powder": 0.8, "packed": 1.0, "transformed": 0.5,
              "hard_groomed": 0.6, "icy": 0.3, "wet": 0.0, "spring": 0.0},
     "durability": 9, "speed": 7, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#1a56db",
     "notes": "All-purpose cold recreational glide — durable and easy to use"},

    {"brand": "Swix", "product": "CH8", "code": "CH8",
     "tier": "recreational", "temp_min": -8.0, "temp_max": 0.0, "humidity_max": 87,
     "snow": {"new": 0.7, "cold_powder": 0.5, "packed": 0.9, "transformed": 1.0,
              "hard_groomed": 0.8, "icy": 0.5, "wet": 0.3, "spring": 0.0},
     "durability": 9, "speed": 7, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#7e3af2",
     "notes": "Medium recreational glide — most used club/recreational wax worldwide"},

    {"brand": "Swix", "product": "CH10", "code": "CH10",
     "tier": "recreational", "temp_min": -4.0, "temp_max": +4.0, "humidity_max": 92,
     "snow": {"new": 0.5, "cold_powder": 0.2, "packed": 0.6, "transformed": 0.9,
              "hard_groomed": 0.5, "icy": 0.4, "wet": 0.8, "spring": 0.4},
     "durability": 9, "speed": 7, "fluoro_free": True, "race_legal": True,
     "application": "iron", "hex": "#f59e0b",
     "notes": "Transitional recreational glide — around zero and wet conditions"},
]


# ---------------------------------------------------------------------------
# KICK WAX (Classic only) — hard wax for dry/cold/groomed conditions
# ---------------------------------------------------------------------------

KICK_WAX: list[dict] = [

    # ── REX ──────────────────────────────────────────────────────────────────
    {"brand": "Rex", "product": "Blue Extra", "code": "R-BX",
     "temp_min": -30.0, "temp_max": -15.0,
     "snow_types": ["new", "cold_powder"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1e3a8a",
     "notes": "Extreme cold, very fine-grained new snow — rarely needed"},

    {"brand": "Rex", "product": "Blue", "code": "R-BL",
     "temp_min": -12.0, "temp_max": -3.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold, fine-grained snow — most common cold kick wax"},

    {"brand": "Rex", "product": "Violet", "code": "R-VI",
     "temp_min": -5.0, "temp_max": 0.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Borderline conditions — medium-cold packed/transformed snow"},

    {"brand": "Rex", "product": "Red", "code": "R-RE",
     "temp_min": -2.0, "temp_max": +2.0,
     "snow_types": ["transformed", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Around freezing, transformed snow"},

    {"brand": "Rex", "product": "Yellow", "code": "R-YE",
     "temp_min": 0.0, "temp_max": +5.0,
     "snow_types": ["wet", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "yellow", "hex": "#c27803",
     "notes": "Soft snow near melting — alternative to klister"},

    # ── SWIX V-Series ────────────────────────────────────────────────────────
    {"brand": "Swix", "product": "V20 Extra Blue", "code": "V20",
     "temp_min": -30.0, "temp_max": -15.0,
     "snow_types": ["new", "cold_powder"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1e3a8a",
     "notes": "Extreme cold new snow"},

    {"brand": "Swix", "product": "V30 Blue", "code": "V30",
     "temp_min": -15.0, "temp_max": -7.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold new or packed snow"},

    {"brand": "Swix", "product": "V40 Violet", "code": "V40",
     "temp_min": -7.0, "temp_max": -1.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Medium cold, packed or transformed"},

    {"brand": "Swix", "product": "V45 Special Violet", "code": "V45",
     "temp_min": -4.0, "temp_max": +1.0,
     "snow_types": ["transformed", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Near-zero borderline conditions — covers icy-to-transformed transition"},

    {"brand": "Swix", "product": "V50 Red", "code": "V50",
     "temp_min": -1.0, "temp_max": +2.0,
     "snow_types": ["transformed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Around freezing, transformed snow"},

    {"brand": "Swix", "product": "V55 Yellow", "code": "V55",
     "temp_min": +1.0, "temp_max": +5.0,
     "snow_types": ["wet", "spring"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "yellow", "hex": "#c27803",
     "notes": "Soft wet snow near melting"},

    # ── VAUHTI Performance Race Grip ─────────────────────────────────────────────────
    {"brand": "Vauhti", "product": "Performance Race Blue", "code": "VP-BL",
     "temp_min": -12.0, "temp_max": -3.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold race kick wax — Finnish race team formula for cold/dry"},

    {"brand": "Vauhti", "product": "Performance Race Violet", "code": "VP-VI",
     "temp_min": -5.0, "temp_max": 0.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Medium-cold race kick — near-zero packed conditions"},

    {"brand": "Vauhti", "product": "Performance Race Red", "code": "VP-RE",
     "temp_min": -2.0, "temp_max": +2.0,
     "snow_types": ["transformed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Around-zero race kick wax"},

    # ── TOKO NF Grip ─────────────────────────────────────────────────────────
    {"brand": "Toko", "product": "NF Grip Blue", "code": "T-BL",
     "temp_min": -12.0, "temp_max": -4.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold kick wax — consistent across cold groomed surfaces"},

    {"brand": "Toko", "product": "NF Grip Violet", "code": "T-VI",
     "temp_min": -6.0, "temp_max": 0.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Medium kick wax — borderline packed/transformed"},

    {"brand": "Toko", "product": "NF Grip Red", "code": "T-RE",
     "temp_min": -2.0, "temp_max": +3.0,
     "snow_types": ["transformed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Warm kick wax — near-zero and mild conditions"},

    # ── RODE ─────────────────────────────────────────────────────────────────
    {"brand": "Rode", "product": "Blue", "code": "RD-BL",
     "temp_min": -14.0, "temp_max": -5.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold kick wax — Italian brand, broad cold range"},

    {"brand": "Rode", "product": "Viola", "code": "RD-VI",
     "temp_min": -6.0, "temp_max": 0.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Medium kick wax"},

    {"brand": "Rode", "product": "Rosso", "code": "RD-RE",
     "temp_min": -2.0, "temp_max": +3.0,
     "snow_types": ["transformed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Warm kick wax"},

    # ── GURU ─────────────────────────────────────────────────────────────────
    {"brand": "Guru", "product": "Green", "code": "GU-GR",
     "temp_min": -30.0, "temp_max": -15.0,
     "snow_types": ["new", "cold_powder"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "green", "hex": "#14532d",
     "notes": "Extreme cold new snow"},

    {"brand": "Guru", "product": "Blue", "code": "GU-BL",
     "temp_min": -15.0, "temp_max": -5.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold kick wax"},

    {"brand": "Guru", "product": "Violet", "code": "GU-VI",
     "temp_min": -5.0, "temp_max": 0.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Medium kick wax — transitional conditions"},

    {"brand": "Guru", "product": "Red", "code": "GU-RE",
     "temp_min": -2.0, "temp_max": +3.0,
     "snow_types": ["transformed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Warm kick wax"},

    # ── START Oslo ───────────────────────────────────────────────────────────
    {"brand": "Start", "product": "Oslo Blue", "code": "ST-BL",
     "temp_min": -12.0, "temp_max": -5.0,
     "snow_types": ["new", "cold_powder", "packed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold kick — Norwegian heritage product, time-tested in Holmenkollen conditions"},

    {"brand": "Start", "product": "Oslo Violet", "code": "ST-VI",
     "temp_min": -5.0, "temp_max": 0.0,
     "snow_types": ["packed", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Medium kick — near-zero groomed conditions"},

    {"brand": "Start", "product": "Oslo Red", "code": "ST-RE",
     "temp_min": -2.0, "temp_max": +3.0,
     "snow_types": ["transformed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": False, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Warm kick"},
]


# ---------------------------------------------------------------------------
# KLISTER — Classic kick for icy/transformed/wet conditions
# ---------------------------------------------------------------------------

KLISTER: list[dict] = [

    # ── REX ──────────────────────────────────────────────────────────────────
    {"brand": "Rex", "product": "Blue Klister", "code": "R-KBL",
     "temp_min": -8.0, "temp_max": -2.0,
     "snow_types": ["icy", "hard_groomed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Hard pack, icy conditions, refrozen crust"},

    {"brand": "Rex", "product": "Violet Klister", "code": "R-KVI",
     "temp_min": -3.0, "temp_max": +2.0,
     "snow_types": ["icy", "hard_groomed", "wet"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Refrozen groomed or hard pack near zero"},

    {"brand": "Rex", "product": "Red Klister", "code": "R-KRE",
     "temp_min": -1.0, "temp_max": +5.0,
     "snow_types": ["wet", "icy"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Wet or icy transformed snow"},

    {"brand": "Rex", "product": "Yellow Klister", "code": "R-KYE",
     "temp_min": +2.0, "temp_max": +10.0,
     "snow_types": ["wet", "spring"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "yellow", "hex": "#c27803",
     "notes": "Wet, slushy, or spring corn snow"},

    # ── SWIX K-Series ────────────────────────────────────────────────────────
    {"brand": "Swix", "product": "K21 Blue Klister", "code": "K21",
     "temp_min": -8.0, "temp_max": -2.0,
     "snow_types": ["icy", "hard_groomed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Ice and hard pack, refrozen crust"},

    {"brand": "Swix", "product": "K22 Purple Klister", "code": "K22",
     "temp_min": -5.0, "temp_max": 0.0,
     "snow_types": ["icy", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Hard pack near zero, icy groomed tracks"},

    {"brand": "Swix", "product": "K25 Violet Klister", "code": "K25",
     "temp_min": -3.0, "temp_max": +2.0,
     "snow_types": ["icy", "wet", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Near-zero icy or wet transformed — most used Swix klister"},

    {"brand": "Swix", "product": "K70 Red Klister", "code": "K70",
     "temp_min": -1.0, "temp_max": +7.0,
     "snow_types": ["wet", "spring"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Wet or slushy conditions"},

    # ── VAUHTI Performance Race Klister ─────────────────────────────────────────────
    {"brand": "Vauhti", "product": "Performance Race Blue Klister", "code": "VK-BL",
     "temp_min": -8.0, "temp_max": -2.0,
     "snow_types": ["icy", "hard_groomed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold icy klister — race-quality formula for hard pack/icy conditions"},

    {"brand": "Vauhti", "product": "Performance Race Violet Klister", "code": "VK-VI",
     "temp_min": -3.0, "temp_max": +2.0,
     "snow_types": ["icy", "wet", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Transition klister — near-zero icy/wet"},

    {"brand": "Vauhti", "product": "Performance Race Red Klister", "code": "VK-RE",
     "temp_min": -1.0, "temp_max": +6.0,
     "snow_types": ["wet", "spring"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Wet/spring race klister"},

    # ── TOKO NF Klister ──────────────────────────────────────────────────────
    {"brand": "Toko", "product": "NF Klister Blue", "code": "TK-BL",
     "temp_min": -8.0, "temp_max": -2.0,
     "snow_types": ["icy", "hard_groomed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold icy klister"},

    {"brand": "Toko", "product": "NF Klister Violet", "code": "TK-VI",
     "temp_min": -3.0, "temp_max": +2.0,
     "snow_types": ["icy", "wet", "transformed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "violet", "hex": "#7e3af2",
     "notes": "Near-zero klister"},

    {"brand": "Toko", "product": "NF Klister Red", "code": "TK-RE",
     "temp_min": -1.0, "temp_max": +6.0,
     "snow_types": ["wet", "spring"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Wet/spring klister"},

    # ── RODE Klister ─────────────────────────────────────────────────────────
    {"brand": "Rode", "product": "Blue Klister", "code": "RK-BL",
     "temp_min": -8.0, "temp_max": -2.0,
     "snow_types": ["icy", "hard_groomed"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "blue", "hex": "#1a56db",
     "notes": "Cold icy/hard pack klister"},

    {"brand": "Rode", "product": "Red Klister", "code": "RK-RE",
     "temp_min": -2.0, "temp_max": +5.0,
     "snow_types": ["wet", "icy", "spring"],
     "fluoro_free": True, "race_legal": True,
     "is_klister": True, "is_binder": False,
     "color": "red", "hex": "#e02424",
     "notes": "Wet or icy transformed snow"},
]


# ---------------------------------------------------------------------------
# BINDERS — Classic kick zone base layer
# ---------------------------------------------------------------------------

BINDERS: list[dict] = [
    {"brand": "Swix", "product": "V05 Base Binder", "code": "V05",
     "temp_min": -30.0, "temp_max": +5.0,
     "use_with_klister": False,
     "hex": "#1f2937",
     "notes": "Hard binder — apply under hard kick wax for durability in classic race prep"},

    {"brand": "Swix", "product": "K65 Klister Binder", "code": "K65",
     "temp_min": -5.0, "temp_max": +10.0,
     "use_with_klister": True,
     "hex": "#374151",
     "notes": "Klister base binder — applied warm before klister for long-lasting adhesion"},

    {"brand": "Rex", "product": "Base Binder", "code": "R-BB",
     "temp_min": -30.0, "temp_max": +3.0,
     "use_with_klister": False,
     "hex": "#1f2937",
     "notes": "Universal hard wax binder — cork in warm before top kick wax"},

    {"brand": "Vauhti", "product": "Binder", "code": "VP-BD",
     "temp_min": -30.0, "temp_max": +5.0,
     "use_with_klister": False,
     "hex": "#1f2937",
     "notes": "Race kick binder — Finnish race team base layer"},

    {"brand": "Toko", "product": "Base Binder", "code": "T-BD",
     "temp_min": -30.0, "temp_max": +3.0,
     "use_with_klister": False,
     "hex": "#1f2937",
     "notes": "Hard wax binder for all kick wax applications"},
]
